package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name = "hoadon", catalog = "datvexemphim")
public class Hoadon implements java.io.Serializable {

	private String maHd;
	private Khachhang khachhang;
	private Phim phim;
	private Phong phong;
	private Suatchieu suatchieu;
	private float soluongve;
	private Date thoigiandat;
	private String vitringoi;

	public Hoadon() {
	}

	public Hoadon(String maHd, float soluongve, Date thoigiandat) {
		this.maHd = maHd;
		this.soluongve = soluongve;
		this.thoigiandat = thoigiandat;
	}

	public Hoadon(String maHd, Khachhang khachhang, Phim phim, Phong phong, Suatchieu suatchieu, float soluongve,
			Date thoigiandat, String vitringoi) {
		this.maHd = maHd;
		this.khachhang = khachhang;
		this.phim = phim;
		this.phong = phong;
		this.suatchieu = suatchieu;
		this.soluongve = soluongve;
		this.thoigiandat = thoigiandat;
		this.vitringoi = vitringoi;
	}

	@Id

	@Column(name = "MaHD", unique = true, nullable = false, length = 20)
	public String getMaHd() {
		return this.maHd;
	}

	public void setMaHd(String maHd) {
		this.maHd = maHd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKH")
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhim")
	public Phim getPhim() {
		return this.phim;
	}

	public void setPhim(Phim phim) {
		this.phim = phim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhong")
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSuat")
	public Suatchieu getSuatchieu() {
		return this.suatchieu;
	}

	public void setSuatchieu(Suatchieu suatchieu) {
		this.suatchieu = suatchieu;
	}

	@Column(name = "Soluongve", nullable = false, precision = 12, scale = 0)
	public float getSoluongve() {
		return this.soluongve;
	}

	public void setSoluongve(float soluongve) {
		this.soluongve = soluongve;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Thoigiandat", nullable = false, length = 19)
	public Date getThoigiandat() {
		return this.thoigiandat;
	}

	public void setThoigiandat(Date thoigiandat) {
		this.thoigiandat = thoigiandat;
	}

	@Column(name = "vitringoi", length = 50)
	public String getVitringoi() {
		return this.vitringoi;
	}

	public void setVitringoi(String vitringoi) {
		this.vitringoi = vitringoi;
	}

}
