package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khachhang generated by hbm2java
 */
@Entity
@Table(name = "khachhang", catalog = "datvexemphim")
public class Khachhang implements java.io.Serializable {

	private String maKh;
	private String hotenKh;
	private String diachiKh;
	private String sdtKh;
	private String tentruycapKh;
	private String matkhauKh;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Khachhang() {
	}

	public Khachhang(String maKh, String hotenKh, String diachiKh, String sdtKh, String tentruycapKh,
			String matkhauKh) {
		this.maKh = maKh;
		this.hotenKh = hotenKh;
		this.diachiKh = diachiKh;
		this.sdtKh = sdtKh;
		this.tentruycapKh = tentruycapKh;
		this.matkhauKh = matkhauKh;
	}

	public Khachhang(String maKh, String hotenKh, String diachiKh, String sdtKh, String tentruycapKh, String matkhauKh,
			Set<Hoadon> hoadons) {
		this.maKh = maKh;
		this.hotenKh = hotenKh;
		this.diachiKh = diachiKh;
		this.sdtKh = sdtKh;
		this.tentruycapKh = tentruycapKh;
		this.matkhauKh = matkhauKh;
		this.hoadons = hoadons;
	}

	@Id

	@Column(name = "MaKH", unique = true, nullable = false, length = 20)
	public String getMaKh() {
		return this.maKh;
	}

	public void setMaKh(String maKh) {
		this.maKh = maKh;
	}

	@Column(name = "HotenKH", nullable = false, length = 50)
	public String getHotenKh() {
		return this.hotenKh;
	}

	public void setHotenKh(String hotenKh) {
		this.hotenKh = hotenKh;
	}

	@Column(name = "DiachiKH", nullable = false, length = 50)
	public String getDiachiKh() {
		return this.diachiKh;
	}

	public void setDiachiKh(String diachiKh) {
		this.diachiKh = diachiKh;
	}

	@Column(name = "SdtKH", nullable = false, length = 10)
	public String getSdtKh() {
		return this.sdtKh;
	}

	public void setSdtKh(String sdtKh) {
		this.sdtKh = sdtKh;
	}

	@Column(name = "TentruycapKH", nullable = false, length = 20)
	public String getTentruycapKh() {
		return this.tentruycapKh;
	}

	public void setTentruycapKh(String tentruycapKh) {
		this.tentruycapKh = tentruycapKh;
	}

	@Column(name = "MatkhauKH", nullable = false, length = 20)
	public String getMatkhauKh() {
		return this.matkhauKh;
	}

	public void setMatkhauKh(String matkhauKh) {
		this.matkhauKh = matkhauKh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachhang")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

}
