package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lichchieu generated by hbm2java
 */
@Entity
@Table(name = "lichchieu", catalog = "datvexemphim")
public class Lichchieu implements java.io.Serializable {

	private String malichchieu;
	private Phim phim;
	private Phong phong;
	private Suatchieu suatchieu;
	private Date ngaychieu;

	public Lichchieu() {
	}

	public Lichchieu(String malichchieu, Date ngaychieu) {
		this.malichchieu = malichchieu;
		this.ngaychieu = ngaychieu;
	}

	public Lichchieu(String malichchieu, Phim phim, Phong phong, Suatchieu suatchieu, Date ngaychieu) {
		this.malichchieu = malichchieu;
		this.phim = phim;
		this.phong = phong;
		this.suatchieu = suatchieu;
		this.ngaychieu = ngaychieu;
	}

	@Id

	@Column(name = "Malichchieu", unique = true, nullable = false, length = 20)
	public String getMalichchieu() {
		return this.malichchieu;
	}

	public void setMalichchieu(String malichchieu) {
		this.malichchieu = malichchieu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhim")
	public Phim getPhim() {
		return this.phim;
	}

	public void setPhim(Phim phim) {
		this.phim = phim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhong")
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSuat")
	public Suatchieu getSuatchieu() {
		return this.suatchieu;
	}

	public void setSuatchieu(Suatchieu suatchieu) {
		this.suatchieu = suatchieu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngaychieu", nullable = false, length = 10)
	public Date getNgaychieu() {
		return this.ngaychieu;
	}

	public void setNgaychieu(Date ngaychieu) {
		this.ngaychieu = ngaychieu;
	}

}
