package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phim generated by hbm2java
 */
@Entity
@Table(name = "phim", catalog = "datvexemphim")
public class Phim implements java.io.Serializable {

	private String maPhim;
	private String tenPhim;
	private String theloai;
	private String daodien;
	private String noidung;
	private Date ngaykhoichieu;
	private String linktrailer;
	private String thoiluong;
	private String hinhanh;
	private Set<Lichchieu> lichchieus = new HashSet<Lichchieu>(0);
	private Set<Ve> ves = new HashSet<Ve>(0);
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Phim() {
	}

	public Phim(String maPhim, String tenPhim, String theloai, String daodien, Date ngaykhoichieu) {
		this.maPhim = maPhim;
		this.tenPhim = tenPhim;
		this.theloai = theloai;
		this.daodien = daodien;
		this.ngaykhoichieu = ngaykhoichieu;
	}

	public Phim(String maPhim, String tenPhim, String theloai, String daodien, String noidung, Date ngaykhoichieu,
			String linktrailer, String thoiluong, String hinhanh, Set<Lichchieu> lichchieus, Set<Ve> ves,
			Set<Hoadon> hoadons) {
		this.maPhim = maPhim;
		this.tenPhim = tenPhim;
		this.theloai = theloai;
		this.daodien = daodien;
		this.noidung = noidung;
		this.ngaykhoichieu = ngaykhoichieu;
		this.linktrailer = linktrailer;
		this.thoiluong = thoiluong;
		this.hinhanh = hinhanh;
		this.lichchieus = lichchieus;
		this.ves = ves;
		this.hoadons = hoadons;
	}

	@Id

	@Column(name = "MaPhim", unique = true, nullable = false, length = 20)
	public String getMaPhim() {
		return this.maPhim;
	}

	public void setMaPhim(String maPhim) {
		this.maPhim = maPhim;
	}

	@Column(name = "TenPhim", nullable = false, length = 50)
	public String getTenPhim() {
		return this.tenPhim;
	}

	public void setTenPhim(String tenPhim) {
		this.tenPhim = tenPhim;
	}

	@Column(name = "Theloai", nullable = false, length = 50)
	public String getTheloai() {
		return this.theloai;
	}

	public void setTheloai(String theloai) {
		this.theloai = theloai;
	}

	@Column(name = "Daodien", nullable = false, length = 50)
	public String getDaodien() {
		return this.daodien;
	}

	public void setDaodien(String daodien) {
		this.daodien = daodien;
	}

	@Column(name = "Noidung")
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngaykhoichieu", nullable = false, length = 10)
	public Date getNgaykhoichieu() {
		return this.ngaykhoichieu;
	}

	public void setNgaykhoichieu(Date ngaykhoichieu) {
		this.ngaykhoichieu = ngaykhoichieu;
	}

	@Column(name = "Linktrailer")
	public String getLinktrailer() {
		return this.linktrailer;
	}

	public void setLinktrailer(String linktrailer) {
		this.linktrailer = linktrailer;
	}

	@Column(name = "Thoiluong", length = 20)
	public String getThoiluong() {
		return this.thoiluong;
	}

	public void setThoiluong(String thoiluong) {
		this.thoiluong = thoiluong;
	}

	@Column(name = "Hinhanh")
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phim")
	public Set<Lichchieu> getLichchieus() {
		return this.lichchieus;
	}

	public void setLichchieus(Set<Lichchieu> lichchieus) {
		this.lichchieus = lichchieus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phim")
	public Set<Ve> getVes() {
		return this.ves;
	}

	public void setVes(Set<Ve> ves) {
		this.ves = ves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phim")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

}
