package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phong generated by hbm2java
 */
@Entity
@Table(name = "phong", catalog = "datvexemphim")
public class Phong implements java.io.Serializable {

	private String maPhong;
	private String tenPhong;
	private float soghe;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);
	private Set<Ve> ves = new HashSet<Ve>(0);
	private Set<Lichchieu> lichchieus = new HashSet<Lichchieu>(0);
	private Set<Suatchieu> suatchieus = new HashSet<Suatchieu>(0);

	public Phong() {
	}

	public Phong(String maPhong, String tenPhong, float soghe) {
		this.maPhong = maPhong;
		this.tenPhong = tenPhong;
		this.soghe = soghe;
	}

	public Phong(String maPhong, String tenPhong, float soghe, Set<Hoadon> hoadons, Set<Ve> ves,
			Set<Lichchieu> lichchieus, Set<Suatchieu> suatchieus) {
		this.maPhong = maPhong;
		this.tenPhong = tenPhong;
		this.soghe = soghe;
		this.hoadons = hoadons;
		this.ves = ves;
		this.lichchieus = lichchieus;
		this.suatchieus = suatchieus;
	}

	@Id

	@Column(name = "MaPhong", unique = true, nullable = false, length = 20)
	public String getMaPhong() {
		return this.maPhong;
	}

	public void setMaPhong(String maPhong) {
		this.maPhong = maPhong;
	}

	@Column(name = "TenPhong", nullable = false, length = 50)
	public String getTenPhong() {
		return this.tenPhong;
	}

	public void setTenPhong(String tenPhong) {
		this.tenPhong = tenPhong;
	}

	@Column(name = "Soghe", nullable = false, precision = 12, scale = 0)
	public float getSoghe() {
		return this.soghe;
	}

	public void setSoghe(float soghe) {
		this.soghe = soghe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<Ve> getVes() {
		return this.ves;
	}

	public void setVes(Set<Ve> ves) {
		this.ves = ves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<Lichchieu> getLichchieus() {
		return this.lichchieus;
	}

	public void setLichchieus(Set<Lichchieu> lichchieus) {
		this.lichchieus = lichchieus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phong")
	public Set<Suatchieu> getSuatchieus() {
		return this.suatchieus;
	}

	public void setSuatchieus(Set<Suatchieu> suatchieus) {
		this.suatchieus = suatchieus;
	}

}
