package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suatchieu generated by hbm2java
 */
@Entity
@Table(name = "suatchieu", catalog = "datvexemphim")
public class Suatchieu implements java.io.Serializable {

	private String maSuat;
	private Phong phong;
	private String giobatdau;
	private String gioketthuc;
	private Set<Lichchieu> lichchieus = new HashSet<Lichchieu>(0);
	private Set<Ve> ves = new HashSet<Ve>(0);
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Suatchieu() {
	}

	public Suatchieu(String maSuat, String giobatdau, String gioketthuc) {
		this.maSuat = maSuat;
		this.giobatdau = giobatdau;
		this.gioketthuc = gioketthuc;
	}

	public Suatchieu(String maSuat, Phong phong, String giobatdau, String gioketthuc, Set<Lichchieu> lichchieus,
			Set<Ve> ves, Set<Hoadon> hoadons) {
		this.maSuat = maSuat;
		this.phong = phong;
		this.giobatdau = giobatdau;
		this.gioketthuc = gioketthuc;
		this.lichchieus = lichchieus;
		this.ves = ves;
		this.hoadons = hoadons;
	}

	@Id

	@Column(name = "MaSuat", unique = true, nullable = false, length = 20)
	public String getMaSuat() {
		return this.maSuat;
	}

	public void setMaSuat(String maSuat) {
		this.maSuat = maSuat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhong")
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	@Column(name = "Giobatdau", nullable = false, length = 20)
	public String getGiobatdau() {
		return this.giobatdau;
	}

	public void setGiobatdau(String giobatdau) {
		this.giobatdau = giobatdau;
	}

	@Column(name = "Gioketthuc", nullable = false, length = 20)
	public String getGioketthuc() {
		return this.gioketthuc;
	}

	public void setGioketthuc(String gioketthuc) {
		this.gioketthuc = gioketthuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suatchieu")
	public Set<Lichchieu> getLichchieus() {
		return this.lichchieus;
	}

	public void setLichchieus(Set<Lichchieu> lichchieus) {
		this.lichchieus = lichchieus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suatchieu")
	public Set<Ve> getVes() {
		return this.ves;
	}

	public void setVes(Set<Ve> ves) {
		this.ves = ves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suatchieu")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

}
