package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "datvexemphim")
public class Taikhoan implements java.io.Serializable {

	private String maTk;
	private String tentruycapTk;
	private String matkhauTk;
	private String phanquyen;

	public Taikhoan() {
	}

	public Taikhoan(String maTk, String tentruycapTk, String matkhauTk, String phanquyen) {
		this.maTk = maTk;
		this.tentruycapTk = tentruycapTk;
		this.matkhauTk = matkhauTk;
		this.phanquyen = phanquyen;
	}

	@Id

	@Column(name = "MaTK", unique = true, nullable = false, length = 20)
	public String getMaTk() {
		return this.maTk;
	}

	public void setMaTk(String maTk) {
		this.maTk = maTk;
	}

	@Column(name = "TentruycapTK", nullable = false, length = 20)
	public String getTentruycapTk() {
		return this.tentruycapTk;
	}

	public void setTentruycapTk(String tentruycapTk) {
		this.tentruycapTk = tentruycapTk;
	}

	@Column(name = "MatkhauTK", nullable = false, length = 20)
	public String getMatkhauTk() {
		return this.matkhauTk;
	}

	public void setMatkhauTk(String matkhauTk) {
		this.matkhauTk = matkhauTk;
	}

	@Column(name = "Phanquyen", nullable = false, length = 20)
	public String getPhanquyen() {
		return this.phanquyen;
	}

	public void setPhanquyen(String phanquyen) {
		this.phanquyen = phanquyen;
	}

}
