package entities;
// Generated Jan 6, 2020 1:50:29 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ve generated by hbm2java
 */
@Entity
@Table(name = "ve", catalog = "datvexemphim")
public class Ve implements java.io.Serializable {

	private String maVe;
	private Loaive loaive;
	private Phim phim;
	private Phong phong;
	private Suatchieu suatchieu;
	private String vitringoi;
	private Date ngayban;

	public Ve() {
	}

	public Ve(String maVe, Date ngayban) {
		this.maVe = maVe;
		this.ngayban = ngayban;
	}

	public Ve(String maVe, Loaive loaive, Phim phim, Phong phong, Suatchieu suatchieu, String vitringoi, Date ngayban) {
		this.maVe = maVe;
		this.loaive = loaive;
		this.phim = phim;
		this.phong = phong;
		this.suatchieu = suatchieu;
		this.vitringoi = vitringoi;
		this.ngayban = ngayban;
	}

	@Id

	@Column(name = "MaVe", unique = true, nullable = false, length = 20)
	public String getMaVe() {
		return this.maVe;
	}

	public void setMaVe(String maVe) {
		this.maVe = maVe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Maloaive")
	public Loaive getLoaive() {
		return this.loaive;
	}

	public void setLoaive(Loaive loaive) {
		this.loaive = loaive;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhim")
	public Phim getPhim() {
		return this.phim;
	}

	public void setPhim(Phim phim) {
		this.phim = phim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPhong")
	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSuat")
	public Suatchieu getSuatchieu() {
		return this.suatchieu;
	}

	public void setSuatchieu(Suatchieu suatchieu) {
		this.suatchieu = suatchieu;
	}

	@Column(name = "Vitringoi", length = 10)
	public String getVitringoi() {
		return this.vitringoi;
	}

	public void setVitringoi(String vitringoi) {
		this.vitringoi = vitringoi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngayban", nullable = false, length = 10)
	public Date getNgayban() {
		return this.ngayban;
	}

	public void setNgayban(Date ngayban) {
		this.ngayban = ngayban;
	}

}
